---
- hosts: all
  become: true
  vars:
    allowed_ssh_networks:
      - 192.168.56.145/24
      - 192.168.56.148/24

    unnecessary_services:
      - postfix
      - telnet
    unnecessary_software:
      - tcpdump
      - nmap-ncat
      - wpa_supplicant
  tasks:
# Task 1: Patching a Software
    - name: Perform full patching
      package:
        name: '*'
        state: latest

#Task 2: Secure Remote Access
    - name: Add admin group
      group:
        name: admin
        state: present

    - name: Add local user
      user:
        name: admin
        group: admin
        shell: /bin/bash
        home: /home/admin
        create_home: yes
        state: present

    - name: Add SSH public key for user
      authorized_key:
        user: admin
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present

    - name: Add sudoer rule for local user
      copy:
        dest: files/etc/sudoers.d/admin
        src: files/etc/sudoers.d/admin
        owner: root
        group: root
        mode: 0440
        validate: /usr/sbin/visudo -csf %s
        remote_src: yes

    - name: Add hardened SSH config
      copy:
        dest: files/etc/ssh/sshd_config
        src: files/etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600
        remote_src: yes
      notify: Reload SSH

    - name: Add SSH port to internal zone
      command: iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      become: true

    - name: Add permitted networks to internal zone
      command: iptables -A INPUT -s {{ item }} -j ACCEPT
      with_items: "{{ allowed_ssh_networks }}"
      become: true

    - name: Drop SSH from the public zone
      command: iptables -D INPUT -p tcp --dport 22 -j ACCEPT
      become: true

    - name: Remove undesirable packages
      package:
        name: "{{ unnecessary_software }}"
        state: absent
      ignore_errors: yes
    - name: Stop and disable unnecessary services if they exist
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items: "{{ unnecessary_services }}"
      ignore_errors: yes
      failed_when: false

#Task 4: Security policy improvements
    - name: Set a message of the day
      copy:
        dest: files/etc/motd
        src: files/etc/motd
        owner: root
        group: root
        mode: 0644
        remote_src: yes

    - name: Set a login banner
      copy:
        dest: "{{ item }}"
        src: files/etc/issue
        owner: root
        group: root
        mode: 0644
      with_items:
        - files/etc/issue
        - files/etc/issue.net
